In [1]:
from os import listdir
from os.path import isfile, join
from json import loads
from re import findall,UNICODE
import sys
sys.path.append("/Users/andyreagan/tools/python")
from kitchentable.dogtoys import *
from labMTsimple.labMTsimple.speedy import *
my_labMT = LabMT()
from labMTsimple.labMTsimple.storyLab import *
import numpy as np
import pandas as pd
import pickle

from tqdm import tqdm

import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
f = open("../data/twitter-labeled-tweets/scrounged/STS-Gold/sts_gold_tweet.csv","r")
print(f.readline().rstrip().split("\";\""))
pos_tweets = []
neg_tweets = []
for line in f:
    a = line.rstrip().split("\";\"")
    if not len(a) == 3:
        print(a)
    tweet_id = a[0].lstrip("\"")
    tweet_pol = a[1]
    tweet_text = a[2].rstrip("\"")
    if int(tweet_pol) == 0:
        neg_tweets.append(tweet_text)
    elif int(tweet_pol) == 4:
        pos_tweets.append(tweet_text)

['"id', 'polarity', 'tweet"']


In [3]:
len(pos_tweets)

632

In [4]:
len(neg_tweets)

1402

In [5]:
pos_tweets[:20]

['@ mcdonalds with my litto sis aka cuzin lol cristyyyyy ',
 '@AnnaSaccone Love your new cards!   I would definitely hire you ;).',
 "@supricky06 that was one of the most enjoyable experiences I've had on YouTube. Well done  http://bit.ly/1a7zPw",
 'Dallas vegas goodness  http://twitpic.com/3lzt1 On my way to to the SusCon ',
 '@JBsFanArgentina Hey I luv this pic!!! was amazing of the last CHAT of The JB in FACEBOOK! ',
 "@llmatticusll yuuuup! 9 miles  it's for cancer! for a good deed!",
 "@seanmurphymusic I'am in love with Taylor Swift's &quot;Crazier&quot; and I think you should definitely do a cover of it, it'll be beautiful  &lt;3",
 'Had a piece of fried chicken, some PSP luv and now off to bed. ',
 "@mileycyrus BRAZIL LOVES U SO MUCH!! YOU ARE AWESOME, MILEY! COME TO BRAZIL.. WE CAN'T FOR THIS DAY COME ",
 "@SilMuri yeah that'd be awesome... You're gonna be the new Oprah! Freakin' yeah  *ninja-rolls over to Sil to eat chocolate*",
 "@DanniAsheOnline Awwww she called me sexy  nice

In [6]:
[listify(x) for x in pos_tweets[:20]]

[['@',
  'mcdonalds',
  'with',
  'my',
  'litto',
  'sis',
  'aka',
  'cuzin',
  'lol',
  'cristyyyyy'],
 ['@annasaccone',
  'love',
  'your',
  'new',
  'cards',
  'i',
  'would',
  'definitely',
  'hire',
  'you',
  ';)'],
 ['@supricky06',
  'that',
  'was',
  'one',
  'of',
  'the',
  'most',
  'enjoyable',
  'experiences',
  "i've",
  'had',
  'on',
  'youtube',
  'well',
  'done',
  'http://bit.ly/1a7zpw'],
 ['dallas',
  'vegas',
  'goodness',
  'http://twitpic.com/3lzt1',
  'on',
  'my',
  'way',
  'to',
  'to',
  'the',
  'suscon'],
 ['@jbsfanargentina',
  'hey',
  'i',
  'luv',
  'this',
  'pic',
  'was',
  'amazing',
  'of',
  'the',
  'last',
  'chat',
  'of',
  'the',
  'jb',
  'in',
  'facebook'],
 ['@llmatticusll',
  'yuuuup',
  '9',
  'miles',
  "it's",
  'for',
  'cancer',
  'for',
  'a',
  'good',
  'deed'],
 ['@seanmurphymusic',
  "i'am",
  'in',
  'love',
  'with',
  'taylor',
  "swift's",
  '&quot',
  ';',
  'crazier&quot',
  ';',
  'and',
  'i',
  'think',
  'you',

In [7]:
neg_tweets[:5]

['the angel is going to miss the athlete this weekend ',
 "It looks as though Shaq is getting traded to Cleveland to play w/ LeBron... Too bad for Suns' fans. The Big Cactus is no more ",
 "@clarianne APRIL 9TH ISN'T COMING SOON ENOUGH ",
 'drinking a McDonalds coffee and not understanding why someone would hurt me for no apparent reason. ',
 'So dissapointed Taylor Swift doesnt have a Twitter ']

In [8]:
all_senti_dicts = [LabMT(),ANEW(),WK(),MPQA(),
                   LIWC01(),LIWC07(),LIWC15(),
                   OL(),PANASX(),Pattern(),SentiWordNet(),
                   AFINN(),GI(),WDAL(),EmoLex(),MaxDiff(),
                   HashtagSent(),Sent140Lex(),SOCAL(),
                   SenticNet(),Emoticons(),SentiStrength(),
                   VADER(),Umigon(),USent(),EmoSenticNet()]

In [9]:
len(all_senti_dicts)

26

In [10]:
for x in [(x.center,x.scorelist.mean()) for x in all_senti_dicts]:
    print(x)

(5.0, 5.3752396791234593)
(5.0, 5.1493520309477763)
(5.0, 5.0638469277757823)
(0.0, -0.27099555061179087)
(0.0, -0.033591731266149873)
(0.0, -0.020968101717599823)
(0.0, -0.015880287066727745)
(0.0, -0.40931878501916841)
(0.0, 0.0)
(0.0, -0.014117423080119412)
(0.0, -0.01176069800289377)
(0.0, -0.5894226887363746)
(0.0, -0.10112978782033619)
(1.5, 1.8397483243737849)
(0.0, -0.071358059512057537)
(0.0, 0.00025610561056105019)
(0.0, 0.063984296772524887)
(0.0, 0.35669409937888202)
(0.0, -0.13250311724152655)
(0.0, -0.030085266666666662)
(0.0, 0.07575757575757576)
(0.0, -1.2795411089866158)
(0.0, -0.18193814982671289)
(0.0, -0.27939590075512405)
(0.0, -0.78716216216216217)
(0.0, 0.59531392174704278)


In [11]:
pos_tweet_dicts = [dictify(listify(x)) for x in pos_tweets]
print(pos_tweet_dicts[0])
for x in all_senti_dicts:
    print("{0:.2f} {2:.2f} {1} ".format(x.score(pos_tweet_dicts[0],center=x.center),
          x.score(pos_tweet_dicts[0],center=1000.0)!=1000.0,
          x.score(pos_tweet_dicts[0],center=x.scorelist.mean())))
    a = np.array([x.score(y) for y in pos_tweet_dicts])
    # print(a)
    b = a[a>x.center]
    c = a[a<x.center]
    print(len(b))

{'@': 1, 'with': 1, 'lol': 1, 'aka': 1, 'litto': 1, 'sis': 1, 'my': 1, 'cuzin': 1, 'mcdonalds': 1, 'cristyyyyy': 1}
6.01 6.01 True 
622
5.00 5.15 False 
396
4.63 4.63 True 
601
0.00 -0.27 False 
441
0.00 0.00 True 
383
0.25 0.25 True 
453
0.25 0.25 True 
462
0.00 -0.41 False 
424
0.00 0.00 False 
13
0.80 0.80 True 
438
0.00 0.00 True 
476
3.00 3.00 True 
469
0.00 -0.10 False 
374
2.11 2.11 True 
628
0.00 -0.07 False 
353
0.25 0.25 True 
579
0.24 0.24 True 
467
0.06 0.06 True 
545
0.00 -0.13 False 
487
0.11 0.11 True 
511
0.00 0.08 False 
12
2.00 2.00 True 
463
1.80 1.80 True 
510
1.00 1.00 True 
404
0.00 -0.79 False 
11
1.00 1.00 True 
585


In [12]:
def classifier_perf(conf_mat,v=False):
    """Given the confusion matrix, produce precision, recall, and f1-score.
    Actual going down, predicited going across."""
    
    N = conf_mat.shape[0]
    # could do these computations using matrix math...
    R = np.array([conf_mat[i,i]/conf_mat[i,:].sum() for i in range(N)])
    P = np.array([conf_mat[i,i]/conf_mat[:,i].sum() for i in range(N)])

    F1 = np.array([2*R[i]*P[i]/(R[i]+P[i]) for i in range(N)])
    if v:
        print(R)
        print(P)
        print(F1)
    return F1.mean()

In [13]:
pos_tweet_dicts = [dictify(listify(x)) for x in pos_tweets]
neg_tweet_dicts = [dictify(listify(x)) for x in neg_tweets]

In [14]:
total_tweets = len(pos_tweet_dicts)+len(neg_tweet_dicts)

In [15]:
tweet_f1 = []
twitter_calibrated_f1 = []
conf_mats = []
for x in all_senti_dicts:
    a = np.array([x.score(y,center=1000.0) for y in pos_tweet_dicts])
    b = np.array([x.score(y,center=1000.0) for y in neg_tweet_dicts])
    total_n_samples = len(a)+len(b)
    a_training = np.random.choice(np.arange(len(a)),size=.05*total_n_samples)
    b_training = np.random.choice(np.arange(len(b)),size=.05*total_n_samples)
    a_mask = np.zeros(len(a))
    b_mask = np.zeros(len(b))
    a_mask[a_training] = 1
    b_mask[b_training] = 1
    avg = np.concatenate((a[(a!=1000.0) & (a_mask>0)],b[(b!=1000.0) & (b_mask>0)])).mean()
    # print(a)
    # b = a[a>x.center]
    # c = a[a<x.center]
    # print(len(b))
    cal_conf_mat = np.zeros((2,2))
    cal_conf_mat[0,0] = len(a[(a!=1000.0) & (a>avg) & (a_mask<1)])
    cal_conf_mat[0,1] = len(a[(a!=1000.0) & (a<avg) & (a_mask<1)])
    cal_conf_mat[1,0] = len(b[(b!=1000.0) & (b>avg) & (b_mask<1)])
    cal_conf_mat[1,1] = len(b[(b!=1000.0) & (b<avg) & (b_mask<1)])
    # classifier_perf(this_conf_mat,v=True)
    # print(a)
    print(cal_conf_mat)
    calibrated_f1 = classifier_perf(cal_conf_mat)
    twitter_calibrated_f1.append(calibrated_f1)
    
    a = np.array([x.score(y,center=1000.0) for y in pos_tweet_dicts])
    # print(a)
    # b = a[a>x.center]
    # c = a[a<x.center]
    # print(len(b))
    this_conf_mat = np.zeros((2,2))
    this_conf_mat[0,0] = len(a[(a!=1000.0) & (a>x.scorelist.mean())])
    this_conf_mat[0,1] = len(a[(a!=1000.0) & (a<x.scorelist.mean())])
    a = np.array([x.score(y,center=1000.0) for y in neg_tweet_dicts])
    this_conf_mat[1,0] = len(a[(a!=1000.0) & (a>x.scorelist.mean())])
    this_conf_mat[1,1] = len(a[(a!=1000.0) & (a<x.scorelist.mean())])
    # classifier_perf(this_conf_mat,v=True)
    # print(a)
    print(this_conf_mat)
    mean_f1 = classifier_perf(this_conf_mat)
    center_conf_mat = np.zeros((2,2))
    a = np.array([x.score(y,center=1000.0) for y in pos_tweet_dicts])
    center_conf_mat[0,0] = len(a[(a!=1000.0) & (a>x.center)])
    center_conf_mat[0,1] = len(a[(a!=1000.0) & (a<x.center)])
    a = np.array([x.score(y,center=1000.0) for y in neg_tweet_dicts])
    center_conf_mat[1,0] = len(a[(a!=1000.0) & (a>x.center)])
    center_conf_mat[1,1] = len(a[(a!=1000.0) & (a<x.center)])
    center_f1 = classifier_perf(center_conf_mat)
    print(center_conf_mat)
    print(x.title,mean_f1,center_f1,calibrated_f1)
    if not np.isnan(center_f1):
        if center_f1>mean_f1:
            conf_mats.append(center_conf_mat)
            tweet_f1.append(center_f1)
            continue
    conf_mats.append(this_conf_mat)
    tweet_f1.append(mean_f1)

/usr/local/lib/python3.5/site-packages/ipykernel/__main__.py:8: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
/usr/local/lib/python3.5/site-packages/ipykernel/__main__.py:9: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


[[  440.    99.]
 [  265.  1036.]]
[[ 589.   43.]
 [ 570.  832.]]
[[  622.    10.]
 [ 1134.   267.]]
labMT 0.694259616042 0.419587009342 0.778985105518
[[ 298.   44.]
 [ 317.  506.]]
[[ 392.   19.]
 [ 433.  459.]]
[[ 396.   15.]
 [ 464.  428.]]
ANEW 0.65218859991 0.632164947238 0.679925812106
[[ 403.  120.]
 [ 340.  913.]]
[[ 598.   18.]
 [ 894.  453.]]
[[ 601.   15.]
 [ 928.  417.]]
WK 0.532856131913 0.514851646197 0.717713010992
[[ 355.  133.]
 [ 290.  932.]]
[[ 546.   29.]
 [ 739.  569.]]
[[ 441.   40.]
 [ 357.  650.]]
MPQA 0.592079341976 0.727829499973 0.720848218817
[[  324.   214.]
 [  163.  1141.]]
[[ 622.   10.]
 [ 867.  533.]]
[[ 383.   10.]
 [ 178.  533.]]
LIWC01 0.567575962066 0.826507377649 0.745206248452
[[  315.   223.]
 [  136.  1169.]]
[[ 623.    9.]
 [ 876.  526.]]
[[ 453.    9.]
 [ 238.  526.]]
LIWC07 0.563904958322 0.797814984774 0.751948106967
[[  397.   143.]
 [  207.  1097.]]
[[ 624.    8.]
 [ 840.  562.]]
[[ 462.    8.]
 [ 224.  562.]]
LIWC15 0.582699781676 0.814

/usr/local/lib/python3.5/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)


[[ 306.  193.]
 [ 253.  943.]]
[[ 538.   46.]
 [ 750.  536.]]
[[ 353.   46.]
 [ 274.  536.]]
EmoLex 0.574331063892 0.729112052161 0.6935988807
[[ 430.   87.]
 [ 416.  796.]]
[[ 579.   29.]
 [ 776.  530.]]
[[ 579.   29.]
 [ 777.  525.]]
MaxDiff 0.57913900456 0.577672896622 0.695432824897
[[ 386.  155.]
 [ 462.  845.]]
[[  399.   233.]
 [  375.  1027.]]
[[ 467.  165.]
 [ 576.  826.]]
HashtagSent 0.669583934047 0.623979392631 0.64417431781
[[  489.    46.]
 [  150.  1155.]]
[[  122.   510.]
 [    3.  1399.]]
[[  545.    87.]
 [   99.  1303.]]
Sent140Lex 0.583693440902 0.893806531873 0.877418556623
[[ 376.   83.]
 [ 280.  806.]]
[[ 494.   47.]
 [ 486.  679.]]
[[ 487.   48.]
 [ 436.  700.]]
SOCAL 0.683855600302 0.705569098232 0.745320996764
[[ 344.  183.]
 [ 408.  857.]]
[[ 521.   99.]
 [ 724.  636.]]
[[ 511.  109.]
 [ 661.  699.]]
SenticNet 0.582936520632 0.60757322417 0.640760558937
[[ 10.   0.]
 [  5.   7.]]
[[ 12.   1.]
 [  7.   9.]]
[[ 12.   0.]
 [  7.   5.]]
Emoticons 0.721153846154 0

In [16]:
for x in sorted(zip([x.title for x in all_senti_dicts],tweet_f1,twitter_calibrated_f1),key=lambda x: x[1]):
    print(x)

('WK', 0.53285613191300163, 0.71771301099210938)
('EmoSenticNet', 0.55963792344098273, 0.59181970608022882)
('WDAL', 0.57851785692140067, 0.63917020892019605)
('MaxDiff', 0.5791390045602357, 0.69543282489664626)
('SenticNet', 0.60757322416974169, 0.64076055893721184)
('ANEW', 0.65218859991023548, 0.67992581210553427)
('HashtagSent', 0.66958393404674399, 0.64417431781010182)
('SentiWordNet', 0.67485065455572668, 0.68009777508591718)
('labMT', 0.69425961604244324, 0.77898510551798061)
('SOCAL', 0.70556909823246228, 0.74532099676448882)
('Pattern', 0.70658157282242962, 0.7537293866628092)
('GI', 0.71928366052251458, 0.70136682861798993)
('Emoticons', 0.72115384615384603, 0.76842105263157889)
('MPQA', 0.72782949997304724, 0.72084821881689787)
('EmoLex', 0.72911205216105401, 0.69359888069985443)
('USent', 0.74444444444444446, 0.72571428571428576)
('VADER', 0.75483326004693074, 0.81040339087784341)
('AFINN', 0.77937331795463272, 0.8013068918156272)
('LIWC07', 0.79781498477379698, 0.751948106

In [17]:
conf_mats[0]

array([[ 589.,   43.],
       [ 570.,  832.]])

In [18]:
conf_mats[0].sum()

2034.0

In [19]:
d = []
for x in sorted(zip([x.title for x in all_senti_dicts],tweet_f1,conf_mats,twitter_calibrated_f1),key=lambda x: x[1]):
    title=x[0]
    acc=x[1]
    perc=x[2].sum()/float(total_tweets)
    acc_total=acc*perc
    print(x[0],x[1],x[2].sum()/float(total_tweets),acc_total)
    d.append([x[0],x[1],x[2].sum()/float(total_tweets),acc_total,x[3]])

WK 0.532856131913 0.965093411996 0.514255942451
EmoSenticNet 0.559637923441 0.959685349066 0.537076315908
WDAL 0.578517856921 0.999016715831 0.577949009471
MaxDiff 0.57913900456 0.941002949853 0.544971511666
SenticNet 0.60757322417 0.973451327434 0.591442961581
ANEW 0.65218859991 0.640609636185 0.417798301712
HashtagSent 0.669583934047 1.0 0.669583934047
SentiWordNet 0.674850654556 0.986234021632 0.665560675044
labMT 0.694259616042 1.0 0.694259616042
SOCAL 0.705569098232 0.821533923304 0.579648949433
Pattern 0.706581572822 0.690265486726 0.487728873276
GI 0.719283660523 0.676499508358 0.486595042713
Emoticons 0.721153846154 0.0142576204523 0.0102819378262
MPQA 0.727829499973 0.731563421829 0.532453439508
EmoLex 0.729112052161 0.594395280236 0.433380762568
USent 0.744444444444 0.0452310717797 0.0336720201027
VADER 0.754833260047 0.812684365782 0.613441189212
AFINN 0.779373317955 0.73598820059 0.573609565869
LIWC07 0.797814984774 0.602753195674 0.480885531629
LIWC15 0.814108256525 0.6175

In [20]:
d

[['WK',
  0.53285613191300163,
  0.96509341199606691,
  0.51425594245094508,
  0.71771301099210938],
 ['EmoSenticNet',
  0.55963792344098273,
  0.95968534906587999,
  0.53707631590796379,
  0.59181970608022882],
 ['WDAL',
  0.57851785692140067,
  0.99901671583087515,
  0.57794900947113381,
  0.63917020892019605],
 ['MaxDiff',
  0.5791390045602357,
  0.94100294985250732,
  0.54497151166582647,
  0.69543282489664626],
 ['SenticNet',
  0.60757322416974169,
  0.97345132743362828,
  0.59144296158116449,
  0.64076055893721184],
 ['ANEW',
  0.65218859991023548,
  0.64060963618485744,
  0.4177983017124075,
  0.67992581210553427],
 ['HashtagSent',
  0.66958393404674399,
  1.0,
  0.66958393404674399,
  0.64417431781010182],
 ['SentiWordNet',
  0.67485065455572668,
  0.98623402163225171,
  0.66556067504365179,
  0.68009777508591718],
 ['labMT', 0.69425961604244324, 1.0, 0.69425961604244324, 0.77898510551798061],
 ['SOCAL',
  0.70556909823246228,
  0.82153392330383479,
  0.57964894943286349,
  0.7

In [21]:
sorted(d,key=lambda x: x[3],reverse=True)

[['Sent140Lex',
  0.89380653187342241,
  1.0,
  0.89380653187342241,
  0.87741855662253865],
 ['labMT', 0.69425961604244324, 1.0, 0.69425961604244324, 0.77898510551798061],
 ['HashtagSent',
  0.66958393404674399,
  1.0,
  0.66958393404674399,
  0.64417431781010182],
 ['SentiWordNet',
  0.67485065455572668,
  0.98623402163225171,
  0.66556067504365179,
  0.68009777508591718],
 ['VADER',
  0.75483326004693074,
  0.81268436578171088,
  0.61344118921218116,
  0.81040339087784341],
 ['SentiStrength',
  0.82612111292962354,
  0.7394296951819076,
  0.61085848271688981,
  0.80909111507722598],
 ['SenticNet',
  0.60757322416974169,
  0.97345132743362828,
  0.59144296158116449,
  0.64076055893721184],
 ['Umigon',
  0.86598922075005613,
  0.67059980334316616,
  0.58073220113228929,
  0.84925527035886761],
 ['SOCAL',
  0.70556909823246228,
  0.82153392330383479,
  0.57964894943286349,
  0.74532099676448882],
 ['WDAL',
  0.57851785692140067,
  0.99901671583087515,
  0.57794900947113381,
  0.6391702

In [22]:
sorted_results = sorted(d,key=lambda x: x[3],reverse=True)

In [29]:
f = open("tables/STS-Gold-results.tex","w")
f.write(r"""\begin{tabular}{l | l | c | c | c | c}
Rank & Dictionary & \% tweets scored & F1 of tweets scored & Calibrated F1 & Overall F1\\
\hline
""")
# strings = []
for i,x in enumerate(sorted_results):
    for j in [1,3,4]:
        if np.isnan(x[j]):
            x[j] = "--"
        else:
            x[j] = "{0:.2f}".format(x[j])
    # strings.append("{4}. & {0} & {1:.1f} & {2:.2f} & {3:.2f}\\\\".format(x[0],x[2]*100,x[1],x[3],i+1))
    f.write("{4}. & {0} & {1:.1f} & {2} & {5} & {3}\\\\\n".format(x[0],x[2]*100,x[1],x[3],i+1,x[4]))
    print("{4}. & {0} & {1:.1f} & {2} & {5} & {3}\\\\".format(x[0],x[2]*100,x[1],x[3],i+1,x[4]))
# f.write("\n".join(strings))
f.write("\\end{tabular}\n")
f.close()

1. & Sent140Lex & 100.0 & 0.89 & 0.88 & 0.89\\
2. & labMT & 100.0 & 0.69 & 0.78 & 0.69\\
3. & HashtagSent & 100.0 & 0.67 & 0.64 & 0.67\\
4. & SentiWordNet & 98.6 & 0.67 & 0.68 & 0.67\\
5. & VADER & 81.3 & 0.75 & 0.81 & 0.61\\
6. & SentiStrength & 73.9 & 0.83 & 0.81 & 0.61\\
7. & SenticNet & 97.3 & 0.61 & 0.64 & 0.59\\
8. & Umigon & 67.1 & 0.87 & 0.85 & 0.58\\
9. & SOCAL & 82.2 & 0.71 & 0.75 & 0.58\\
10. & WDAL & 99.9 & 0.58 & 0.64 & 0.58\\
11. & AFINN & 73.6 & 0.78 & 0.80 & 0.57\\
12. & OL & 66.7 & 0.83 & 0.82 & 0.55\\
13. & MaxDiff & 94.1 & 0.58 & 0.70 & 0.54\\
14. & EmoSenticNet & 96.0 & 0.56 & 0.59 & 0.54\\
15. & MPQA & 73.2 & 0.73 & 0.72 & 0.53\\
16. & WK & 96.5 & 0.53 & 0.72 & 0.51\\
17. & LIWC15 & 61.8 & 0.81 & 0.78 & 0.50\\
18. & Pattern & 69.0 & 0.71 & 0.75 & 0.49\\
19. & GI & 67.6 & 0.72 & 0.70 & 0.49\\
20. & LIWC07 & 60.3 & 0.80 & 0.75 & 0.48\\
21. & LIWC01 & 54.3 & 0.83 & 0.75 & 0.45\\
22. & EmoLex & 59.4 & 0.73 & 0.69 & 0.43\\
23. & ANEW & 64.1 & 0.65 & 0.68 & 0.42\\
24. & 

In [24]:
all_results = np.array([x[3] for x in d])

In [25]:
all_results.mean()

0.50190056235638225

In [26]:
np.median(all_results)

0.54102391378689507

In [27]:
classifier_perf(np.ones((2,2)))

0.5